import { VideoMetadata } from "../types";

/**
 * YouTube Video Upload Service — Complete rewrite.
 *
 * Uses the YouTube Data API v3 Resumable Upload protocol:
 * 1. POST metadata → get resumable upload URI
 * 2. PUT video bytes → get video ID
 * 3. POST thumbnail (optional)
 *
 * All errors are caught with clear, actionable Portuguese messages.
 */
export const uploadVideoToYouTube = async (
    accessToken: string,
    videoFile: File,
    metadata: VideoMetadata,
    thumbnailUrl?: string,
    scheduledDate?: string,
    onProgress?: (percent: number) => void
): Promise<string> => {

    if (!accessToken) throw new Error("Token de acesso ausente. Reconecte seu canal do YouTube em Configurações.");
    if (!videoFile || videoFile.size === 0) throw new Error("Arquivo de vídeo inválido ou vazio.");

    // ── 1. Build metadata ────────────────────────────
    let title = (metadata?.youtubeTitle || "Untitled Video").substring(0, 100);
    let description = (metadata?.youtubeDescription || "Generated by DarkStream AI").substring(0, 5000);

    if (metadata?.isShorts) {
        if (!title.toLowerCase().includes('#shorts')) title = `${title.substring(0, 92)} #Shorts`.trim();
        if (!description.toLowerCase().includes('#shorts')) description = `${description}\n\n#Shorts`.trim();
    }

    const privacyStatus = scheduledDate ? "private" : (metadata?.visibility || "private");

    const body: any = {
        snippet: {
            title,
            description,
            tags: metadata?.tags || [],
            categoryId: metadata?.categoryId || "24",
        },
        status: {
            privacyStatus,
            selfDeclaredMadeForKids: false,
            embeddable: true,
        },
    };

    if (scheduledDate) {
        const d = new Date(scheduledDate);
        if (isNaN(d.getTime())) throw new Error("Data de agendamento inválida.");
        body.status.publishAt = d.toISOString();
        body.status.privacyStatus = "private";
    }

    // ── 2. Request resumable upload URI ──────────────
    console.log(`[YouTube] Iniciando upload (${(videoFile.size / 1024 / 1024).toFixed(1)} MB)…`);

    const initRes = await safeFetch(
        `https://www.googleapis.com/upload/youtube/v3/videos?uploadType=resumable&part=snippet,status,contentDetails`,
        {
            method: "POST",
            headers: {
                Authorization: `Bearer ${accessToken}`,
                "Content-Type": "application/json",
                "X-Upload-Content-Length": videoFile.size.toString(),
                "X-Upload-Content-Type": videoFile.type || "video/mp4",
            },
            body: JSON.stringify(body),
        }
    );

    if (!initRes.ok) {
        await handleYouTubeError(initRes, "iniciar upload");
    }

    const uploadUrl = initRes.headers.get("Location");
    if (!uploadUrl) throw new Error("YouTube não retornou URL de upload. Tente novamente.");

    // ── 3. Upload video bytes via XHR (for progress) ─
    console.log("[YouTube] Enviando vídeo…");
    const videoId = await uploadWithProgress(uploadUrl, videoFile, onProgress);
    console.log(`[YouTube] ✅ Vídeo enviado: ${videoId}`);

    // ── 4. Upload thumbnail (best-effort) ────────────
    if (videoId && thumbnailUrl && thumbnailUrl.startsWith("data:")) {
        await uploadThumbnail(accessToken, videoId, thumbnailUrl);
    }

    if (onProgress) onProgress(100);
    return videoId;
};

// ─────────────────────────────────────────────────────
// INTERNAL HELPERS
// ─────────────────────────────────────────────────────

/**
 * Wrapper around fetch that converts network errors into clear messages.
 */
async function safeFetch(url: string, init: RequestInit): Promise<Response> {
    try {
        return await fetch(url, init);
    } catch (e: any) {
        const origin = typeof window !== "undefined" ? window.location.origin : "desconhecido";

        if (e.message === "Failed to fetch" || e.name === "TypeError") {
            throw new Error(
                `Erro de conexão (CORS/Rede). Verifique se:\n` +
                `1. O domínio "${origin}" está nas "Origens JavaScript autorizadas" no Google Cloud Console.\n` +
                `2. O app OAuth está em modo "Produção" (não "Teste").\n` +
                `3. Sua internet está funcionando.`
            );
        }
        throw new Error(`Erro de rede: ${e.message}`);
    }
}

/**
 * Parse YouTube API error responses into actionable messages.
 */
async function handleYouTubeError(res: Response, action: string): Promise<never> {
    let detail = "";
    let code = res.status;

    try {
        const json = await res.json();
        detail = json.error?.message || JSON.stringify(json.error || json);
        code = json.error?.code || code;
    } catch {
        detail = await res.text().catch(() => "");
    }

    const detailLower = detail.toLowerCase();

    switch (code) {
        case 401:
            throw new Error(
                "Token expirado (401). Vá em Configurações → desconecte e reconecte seu canal do YouTube."
            );
        case 403:
            if (detailLower.includes("quota")) {
                throw new Error(
                    "Cota diária da API do YouTube excedida (403). " +
                    "Projetos novos têm limite de ~6 vídeos/dia. Aguarde 24h ou solicite aumento de cota no Google Cloud Console."
                );
            }
            if (detailLower.includes("permission") || detailLower.includes("access") || detailLower.includes("forbidden")) {
                throw new Error(
                    "Acesso negado (403). Verifique se:\n" +
                    "1. Você autorizou a permissão 'Gerenciar seus vídeos do YouTube' no login.\n" +
                    "2. O escopo 'youtube.upload' está ativo no Google Cloud Console.\n" +
                    "3. O app OAuth está em modo 'Produção'."
                );
            }
            throw new Error(`Erro 403 ao ${action}: ${detail}`);
        case 400:
            throw new Error(`Requisição inválida (400) ao ${action}: ${detail}`);
        default:
            throw new Error(`Erro ${code} ao ${action}: ${detail || "Erro desconhecido"}`);
    }
}

/**
 * Upload file with XHR for progress tracking.
 * Returns the YouTube video ID.
 */
function uploadWithProgress(url: string, file: File, onProgress?: (pct: number) => void): Promise<string> {
    return new Promise((resolve, reject) => {
        const xhr = new XMLHttpRequest();
        xhr.open("PUT", url, true);
        xhr.setRequestHeader("Content-Type", file.type || "video/mp4");

        xhr.upload.onprogress = (e) => {
            if (e.lengthComputable && onProgress) {
                onProgress(Math.round((e.loaded / e.total) * 100));
            }
        };

        xhr.onload = () => {
            if (xhr.status >= 200 && xhr.status < 300) {
                try {
                    const resp = JSON.parse(xhr.responseText);
                    if (!resp.id) reject(new Error("YouTube não retornou ID do vídeo na resposta."));
                    else resolve(resp.id);
                } catch {
                    reject(new Error("Resposta inválida do YouTube após upload."));
                }
            } else {
                let msg = `Upload falhou (status ${xhr.status})`;
                try { msg = JSON.parse(xhr.responseText).error?.message || msg; } catch {}
                reject(new Error(msg));
            }
        };

        xhr.onerror = () => reject(new Error("Erro de rede durante o upload do vídeo."));
        xhr.onabort = () => reject(new Error("Upload cancelado."));
        xhr.send(file);
    });
}

/**
 * Upload thumbnail — best effort, never blocks the pipeline.
 */
async function uploadThumbnail(token: string, videoId: string, dataUrl: string) {
    console.log("[YouTube] Enviando thumbnail…");
    try {
        const blob = await (await fetch(dataUrl)).blob();
        const res = await fetch(
            `https://www.googleapis.com/upload/youtube/v3/thumbnails/set?videoId=${videoId}`,
            {
                method: "POST",
                headers: {
                    Authorization: `Bearer ${token}`,
                    "Content-Type": blob.type || "image/jpeg",
                },
                body: blob,
            }
        );
        if (res.ok) {
            console.log("[YouTube] ✅ Thumbnail enviada.");
        } else {
            const err = await res.json().catch(() => ({}));
            console.warn("[YouTube] ⚠️ Falha na thumbnail:", err.error?.message || res.status);
        }
    } catch (e: any) {
        console.warn("[YouTube] ⚠️ Erro ao enviar thumbnail:", e.message);
    }
}
