import { VideoMetadata } from "../types";

/**
 * Uploads a video to YouTube using the Data API v3.
 * Supports Resumable Upload with Progress Tracking.
 */
export const uploadVideoToYouTube = async (
    accessToken: string,
    videoFile: File,
    metadata: VideoMetadata,
    thumbnailUrl?: string,
    scheduledDate?: string,
    onProgress?: (percent: number) => void
): Promise<string> => {
    
    let finalTitle = (metadata?.youtubeTitle || "Untitled Video").substring(0, 100);
    let finalDescription = (metadata?.youtubeDescription || "Generated by DarkStream AI").substring(0, 5000);

    if (metadata?.isShorts) {
        if (!finalTitle.toLowerCase().includes('#shorts')) {
            finalTitle = (finalTitle.substring(0, 92) + " #Shorts").trim();
        }
        if (!finalDescription.toLowerCase().includes('#shorts')) {
            finalDescription = (finalDescription + "\n\n#Shorts").trim();
        }
    }

    const snippet: any = {
        title: finalTitle,
        description: finalDescription,
        tags: metadata?.tags || [],
        categoryId: metadata?.categoryId || "24",
    };

    const status: any = {
        privacyStatus: scheduledDate ? "private" : (metadata?.visibility || "private"),
        selfDeclaredMadeForKids: false,
        embeddable: true,
    };

    if (scheduledDate) {
        const date = new Date(scheduledDate);
        if (isNaN(date.getTime())) {
            throw new Error("Data de agendamento inválida.");
        }
        status.publishAt = date.toISOString();
        status.privacyStatus = "private";
    }

    const requestBody = { snippet, status };

    console.log(`[YouTube Service] Iniciando upload de ${videoFile.size} bytes...`);

    let initRes;
    try {
        console.log("[YouTube Service] Solicitando URL de upload resumível...");
        initRes = await fetch(`https://www.googleapis.com/upload/youtube/v3/videos?uploadType=resumable&part=snippet,status,contentDetails`, {
            method: 'POST',
            headers: {
                'Authorization': `Bearer ${accessToken}`,
                'Content-Type': 'application/json',
                'X-Upload-Content-Length': videoFile.size.toString(),
                'X-Upload-Content-Type': videoFile.type || 'video/mp4'
            },
            body: JSON.stringify(requestBody)
        });
    } catch (e: any) {
        console.error("YouTube Fetch Error (Step A):", e);
        const origin = typeof window !== 'undefined' ? window.location.origin : 'seu domínio';
        
        const isNetworkError = e.message === 'Failed to fetch' || e.name === 'TypeError';
        
        if (isNetworkError) {
            throw new Error(`Falha na conexão com o Google (CORS/Rede). Certifique-se de que o domínio "${origin}" está na lista de 'Origens JavaScript autorizadas' no seu Console do Google Cloud e que o Client ID está correto.`);
        }
        throw new Error(`Erro de conexão: ${e.message}`);
    }

    if (!initRes.ok) {
        const err = await initRes.json();
        console.error("YouTube Init Error Response:", err);
        
        const errorDetail = err.error?.message || "";
        const errorCode = err.error?.code || initRes.status;
        
        if (errorCode === 401) {
            throw new Error("Sessão Expirada (401): Sua conexão com o YouTube expirou. Por favor, vá em 'Configurações', desconecte e conecte seu canal novamente para renovar o token.");
        }
        
        if (errorCode === 403) {
            if (errorDetail.toLowerCase().includes('quota')) {
                throw new Error("Cota Excedida (403): Você atingiu o limite diário de uploads da API do YouTube. Isso é comum em projetos novos (limite de ~6 vídeos/dia). Tente novamente em 24 horas ou solicite aumento de cota no Google Cloud Console.");
            }
            if (errorDetail.toLowerCase().includes('permission') || errorDetail.toLowerCase().includes('access')) {
                throw new Error(`Acesso Negado (403): O Google recusou o upload. Verifique se: 1) Você marcou a caixa de permissão 'Gerenciar seus vídeos do YouTube' na tela de login. 2) Sua conta do YouTube não possui restrições ou avisos. 3) O escopo 'youtube.upload' está ativo no seu projeto do Google Cloud.`);
            }
            throw new Error(`Erro 403: ${errorDetail || 'Acesso negado. Verifique as permissões do seu App no Google Cloud Console.'}`);
        }

        if (errorCode === 400) {
            throw new Error(`Requisição Inválida (400): ${errorDetail}. Verifique se o título e a descrição não possuem caracteres proibidos e se o arquivo de vídeo é válido.`);
        }

        throw new Error(`Falha ao iniciar upload (Erro ${errorCode}): ${errorDetail || 'Erro desconhecido na API do YouTube.'}`);
    }

    const uploadUrl = initRes.headers.get('Location');
    if (!uploadUrl) throw new Error("Não foi possível obter a URL de upload do YouTube.");

    const videoId = await new Promise<string>((resolve, reject) => {
        const xhr = new XMLHttpRequest();
        xhr.open('PUT', uploadUrl, true);
        xhr.setRequestHeader('Content-Type', videoFile.type);

        xhr.upload.onprogress = (e) => {
            if (e.lengthComputable && onProgress) {
                const percentComplete = (e.loaded / e.total) * 100;
                onProgress(Math.round(percentComplete));
            }
        };

        xhr.onload = () => {
            if (xhr.status >= 200 && xhr.status < 300) {
                try {
                    const response = JSON.parse(xhr.responseText);
                    console.log("[YouTube Service] Upload concluído com sucesso:", response.id);
                    resolve(response.id);
                } catch (e) {
                    reject(new Error("Resposta inválida do YouTube após o upload."));
                }
            } else {
                let errorMsg = `Upload falhou com status ${xhr.status}`;
                try {
                    const err = JSON.parse(xhr.responseText);
                    errorMsg = err.error?.message || errorMsg;
                } catch(e) {}
                reject(new Error(errorMsg));
            }
        };

        xhr.onerror = () => reject(new Error("Erro de rede durante o upload do arquivo de vídeo."));
        xhr.onabort = () => reject(new Error("Upload cancelado pelo usuário ou pelo navegador."));
        
        xhr.send(videoFile);
    });

    if (videoId && thumbnailUrl && thumbnailUrl.startsWith('data:')) {
        console.log("[YouTube Service] Enviando thumbnail...");
        if (onProgress) onProgress(99);
        try {
            const thumbRes = await fetch(thumbnailUrl);
            const thumbBlob = await thumbRes.blob();
            
            const thumbUploadRes = await fetch(`https://www.googleapis.com/upload/youtube/v3/thumbnails/set?videoId=${videoId}`, {
                method: 'POST',
                headers: {
                    'Authorization': `Bearer ${accessToken}`,
                    'Content-Type': thumbBlob.type
                },
                body: thumbBlob
            });
            
            if (!thumbUploadRes.ok) {
                const thumbErr = await thumbUploadRes.json();
                console.warn("Falha ao enviar thumbnail:", thumbErr);
            } else {
                console.log("[YouTube Service] Thumbnail enviada com sucesso.");
            }
        } catch (e) {
            console.warn("Erro ao processar thumbnail para upload:", e);
        }
    }
    
    if (onProgress) onProgress(100);
    return videoId;
};
