import { VideoMetadata } from "../types";

/**
 * YouTube Upload Service v3 — Complete rewrite.
 *
 * Flow:
 * 1. Validate inputs
 * 2. POST metadata → get resumable upload URI
 * 3. PUT video bytes with progress tracking via XHR
 * 4. POST thumbnail (best-effort)
 *
 * All errors are surfaced with clear, actionable Portuguese messages.
 */

// ─────────────────────────────────────────────────────
// PUBLIC API
// ─────────────────────────────────────────────────────

export const uploadVideoToYouTube = async (
    accessToken: string,
    videoFile: File,
    metadata: VideoMetadata,
    thumbnailUrl?: string,
    scheduledDate?: string,
    onProgress?: (percent: number) => void
): Promise<string> => {

    // ── 0. Input validation ──────────────────────────
    if (!accessToken || accessToken.trim().length < 10) {
        throw new Error("Token de acesso ausente ou inválido. Vá em Configurações → desconecte e reconecte seu canal do YouTube.");
    }
    if (!videoFile || videoFile.size === 0) {
        throw new Error("Arquivo de vídeo inválido ou vazio. Verifique se o vídeo foi renderizado corretamente.");
    }
    if (videoFile.size > 128 * 1024 * 1024 * 1024) {
        throw new Error("Arquivo excede o limite de 128 GB do YouTube.");
    }

    // ── 1. Verify token is still valid ───────────────
    console.log("[YouTube] Verificando token de acesso…");
    await verifyAccessToken(accessToken);

    // ── 2. Build metadata body ───────────────────────
    let title = (metadata?.youtubeTitle || "Untitled Video").substring(0, 100);
    let description = (metadata?.youtubeDescription || "Generated by DarkStream AI").substring(0, 5000);

    if (metadata?.isShorts) {
        if (!title.toLowerCase().includes('#shorts')) title = `${title.substring(0, 92)} #Shorts`.trim();
        if (!description.toLowerCase().includes('#shorts')) description = `${description}\n\n#Shorts`.trim();
    }

    const privacyStatus = scheduledDate ? "private" : (metadata?.visibility || "private");

    const body: Record<string, any> = {
        snippet: {
            title,
            description,
            tags: (metadata?.tags || []).slice(0, 500), // YouTube max 500 tags
            categoryId: metadata?.categoryId || "24",
        },
        status: {
            privacyStatus,
            selfDeclaredMadeForKids: false,
            embeddable: true,
        },
    };

    if (scheduledDate) {
        const d = new Date(scheduledDate);
        if (isNaN(d.getTime())) throw new Error("Data de agendamento inválida. Use o formato correto.");
        if (d.getTime() < Date.now()) throw new Error("A data de agendamento deve ser no futuro.");
        body.status.publishAt = d.toISOString();
        body.status.privacyStatus = "private"; // YouTube requires private for scheduling
    }

    // ── 3. Request resumable upload URI ──────────────
    const fileSizeMB = (videoFile.size / 1024 / 1024).toFixed(1);
    console.log(`[YouTube] Iniciando upload resumável (${fileSizeMB} MB, tipo: ${videoFile.type || 'video/mp4'})…`);
    if (onProgress) onProgress(2);

    const initRes = await safeFetch(
        `https://www.googleapis.com/upload/youtube/v3/videos?uploadType=resumable&part=snippet,status`,
        {
            method: "POST",
            headers: {
                Authorization: `Bearer ${accessToken}`,
                "Content-Type": "application/json; charset=UTF-8",
                "X-Upload-Content-Length": videoFile.size.toString(),
                "X-Upload-Content-Type": videoFile.type || "video/mp4",
            },
            body: JSON.stringify(body),
        }
    );

    if (!initRes.ok) {
        await handleYouTubeError(initRes, "iniciar upload");
    }

    const uploadUrl = initRes.headers.get("Location");
    if (!uploadUrl) {
        throw new Error("YouTube não retornou URL de upload resumável. Tente novamente em alguns segundos.");
    }

    console.log("[YouTube] URL de upload obtida. Enviando vídeo…");
    if (onProgress) onProgress(5);

    // ── 4. Upload video bytes via XHR (for progress) ─
    const videoId = await uploadWithProgress(uploadUrl, videoFile, accessToken, onProgress);
    console.log(`[YouTube] ✅ Vídeo enviado com sucesso! ID: ${videoId}`);

    // ── 5. Upload thumbnail (best-effort) ────────────
    if (videoId && thumbnailUrl) {
        if (onProgress) onProgress(92);
        await uploadThumbnail(accessToken, videoId, thumbnailUrl);
    }

    // ── 6. Wait for YouTube to finish processing ─────
    if (videoId) {
        if (onProgress) onProgress(95);
        console.log('[YouTube] Aguardando processamento do YouTube...');
        try {
            await waitForProcessing(accessToken, videoId, onProgress);
        } catch (e: any) {
            // Non-fatal: video was uploaded, just log the processing issue
            console.warn('[YouTube] Aviso de processamento:', e.message);
        }
    }

    if (onProgress) onProgress(100);
    return videoId;
};

/**
 * Quick check: can we hit YouTube API with this token?
 */
export const verifyYouTubeToken = async (token: string): Promise<boolean> => {
    try {
        const res = await fetch(
            "https://www.googleapis.com/youtube/v3/channels?part=id&mine=true",
            { headers: { Authorization: `Bearer ${token}` } }
        );
        return res.ok;
    } catch {
        return false;
    }
};

// ─────────────────────────────────────────────────────
// INTERNAL HELPERS
// ─────────────────────────────────────────────────────

/**
 * Verify the access token is valid before starting the upload.
 */
async function verifyAccessToken(token: string): Promise<void> {
    try {
        const res = await fetch(
            "https://www.googleapis.com/youtube/v3/channels?part=id&mine=true",
            { headers: { Authorization: `Bearer ${token}` } }
        );
        if (res.status === 401) {
            throw new Error(
                "Token expirado (401). Vá em Configurações → desconecte e reconecte seu canal do YouTube para obter um novo token."
            );
        }
        if (res.status === 403) {
            const json = await res.json().catch(() => ({}));
            const msg = json.error?.message || "";
            if (msg.toLowerCase().includes("quota")) {
                throw new Error(
                    "Cota diária da API do YouTube excedida. Projetos novos têm limite de ~6 vídeos/dia. Aguarde 24h ou solicite aumento no Google Cloud Console."
                );
            }
            throw new Error(
                "Acesso negado (403). Verifique se autorizou a permissão 'Gerenciar seus vídeos do YouTube' e se o app está em modo Produção no Google Cloud Console."
            );
        }
        if (!res.ok) {
            throw new Error(`Erro ao verificar token: HTTP ${res.status}`);
        }
    } catch (e: any) {
        if (e.message.includes("Token") || e.message.includes("Cota") || e.message.includes("Acesso")) throw e;
        throw new Error(
            `Não foi possível verificar o token do YouTube. Verifique sua conexão de internet. (${e.message})`
        );
    }
}

/**
 * Wrapper around fetch that converts network/CORS errors into clear messages.
 */
async function safeFetch(url: string, init: RequestInit): Promise<Response> {
    try {
        return await fetch(url, init);
    } catch (e: any) {
        const origin = typeof window !== "undefined" ? window.location.origin : "desconhecido";

        if (e.message === "Failed to fetch" || e.name === "TypeError") {
            throw new Error(
                `Erro de conexão (CORS/Rede). Para corrigir:\n` +
                `1. Vá em Google Cloud Console → Credenciais → seu ID do cliente OAuth.\n` +
                `2. Adicione "${origin}" em "Origens JavaScript autorizadas".\n` +
                `3. Certifique-se de que o app OAuth está em modo "Produção".\n` +
                `4. Aguarde 5 minutos após salvar as mudanças.`
            );
        }
        throw new Error(`Erro de rede inesperado: ${e.message}`);
    }
}

/**
 * Parse YouTube API error responses into actionable Portuguese messages.
 */
async function handleYouTubeError(res: Response, action: string): Promise<never> {
    let detail = "";
    let code = res.status;

    try {
        const json = await res.json();
        detail = json.error?.message || JSON.stringify(json.error || json);
        code = json.error?.code || code;
    } catch {
        detail = await res.text().catch(() => "Sem detalhes disponíveis");
    }

    const detailLower = detail.toLowerCase();

    switch (code) {
        case 400:
            if (detailLower.includes("api key")) {
                throw new Error("Erro 400: Chave de API inválida. Verifique as credenciais no Google Cloud Console.");
            }
            throw new Error(`Requisição inválida (400) ao ${action}: ${detail}\n\nVerifique se o título e descrição do vídeo são válidos.`);
        
        case 401:
            throw new Error(
                "Token expirado ou revogado (401). Vá em Configurações → desconecte e reconecte seu canal do YouTube."
            );
        
        case 403:
            if (detailLower.includes("quota")) {
                throw new Error(
                    "Cota diária da API do YouTube excedida (403). " +
                    "Projetos novos têm limite de ~6 vídeos/dia. Aguarde 24 horas ou solicite aumento de cota no Google Cloud Console."
                );
            }
            if (detailLower.includes("permission") || detailLower.includes("access") || detailLower.includes("forbidden") || detailLower.includes("insufficient")) {
                throw new Error(
                    "Permissão insuficiente (403). Verifique:\n" +
                    "1. Você autorizou o escopo 'Gerenciar seus vídeos do YouTube' no login.\n" +
                    "2. A YouTube Data API v3 está habilitada no Google Cloud Console.\n" +
                    "3. O app OAuth está em modo 'Produção' (não 'Teste')."
                );
            }
            throw new Error(`Erro 403 ao ${action}: ${detail}`);
        
        case 404:
            throw new Error(`Recurso não encontrado (404) ao ${action}. Verifique se a YouTube Data API está habilitada.`);
        
        case 429:
            throw new Error("Muitas requisições (429). Aguarde alguns minutos antes de tentar novamente.");
        
        case 500:
        case 502:
        case 503:
            throw new Error(`Servidor do YouTube temporariamente indisponível (${code}). Tente novamente em alguns minutos.`);
        
        default:
            throw new Error(`Erro ${code} ao ${action}: ${detail || "Erro desconhecido do YouTube"}`);
    }
}

/**
 * Poll YouTube until video finishes processing (or timeout).
 * YouTube can take 1-10 min to go from "uploaded" to "processed".
 */
async function waitForProcessing(
    accessToken: string,
    videoId: string,
    onProgress?: (pct: number) => void,
    timeoutMs = 10 * 60 * 1000 // 10 min max
): Promise<void> {
    const start = Date.now();
    let attempt = 0;

    while (Date.now() - start < timeoutMs) {
        attempt++;
        await new Promise(r => setTimeout(r, 8000)); // poll every 8s

        try {
            const res = await fetch(
                `https://www.googleapis.com/youtube/v3/videos?part=processingDetails,status&id=${videoId}`,
                { headers: { Authorization: `Bearer ${accessToken}` } }
            );
            if (!res.ok) break;

            const data = await res.json();
            const video = data.items?.[0];
            if (!video) break;

            const uploadStatus = video.processingDetails?.processingStatus;
            const privacyStatus = video.status?.uploadStatus;

            console.log(`[YouTube] Processing status: ${uploadStatus || privacyStatus} (attempt ${attempt})`);

            if (uploadStatus === 'succeeded' || privacyStatus === 'processed' || privacyStatus === 'uploaded') {
                if (onProgress) onProgress(100);
                return;
            }
            if (uploadStatus === 'failed' || privacyStatus === 'failed' || privacyStatus === 'rejected') {
                throw new Error(`YouTube processamento falhou: ${uploadStatus || privacyStatus}`);
            }

            // Update progress during processing (90-99%)
            if (onProgress) onProgress(90 + Math.min(9, attempt));
        } catch (e: any) {
            if (e.message.includes('falhou')) throw e;
            console.warn('[YouTube] Polling error (non-fatal):', e.message);
        }
    }
    // Timeout — video was uploaded, just not confirmed as processed yet
    console.warn('[YouTube] Processing poll timed out — video was uploaded successfully but processing may still be ongoing.');
}

/**
 * Upload file with XHR for real-time progress tracking.
 * Returns the YouTube video ID.
 */
function uploadWithProgress(
    url: string, 
    file: File, 
    accessToken: string,
    onProgress?: (pct: number) => void
): Promise<string> {
    return new Promise((resolve, reject) => {
        const xhr = new XMLHttpRequest();
        xhr.open("PUT", url, true);
        xhr.setRequestHeader("Content-Type", file.type || "video/mp4");
        xhr.setRequestHeader("Content-Length", file.size.toString());

        xhr.upload.onprogress = (e) => {
            if (e.lengthComputable && onProgress) {
                // Map upload progress to 5-90% range
                const uploadPct = Math.round((e.loaded / e.total) * 85) + 5;
                onProgress(Math.min(90, uploadPct));
            }
        };

        xhr.onload = () => {
            if (xhr.status >= 200 && xhr.status < 300) {
                try {
                    const resp = JSON.parse(xhr.responseText);
                    if (!resp.id) {
                        reject(new Error("YouTube processou o upload mas não retornou ID do vídeo. Verifique no YouTube Studio se o vídeo foi criado."));
                    } else {
                        resolve(resp.id);
                    }
                } catch {
                    reject(new Error("Resposta inválida do YouTube após upload. O vídeo pode ter sido enviado — verifique no YouTube Studio."));
                }
            } else if (xhr.status === 401) {
                reject(new Error("Token expirou durante o upload. Reconecte seu canal nas Configurações e tente novamente."));
            } else if (xhr.status === 403) {
                let msg = "Permissão negada durante upload";
                try { msg = JSON.parse(xhr.responseText).error?.message || msg; } catch {}
                reject(new Error(`Erro 403: ${msg}`));
            } else if (xhr.status >= 500) {
                reject(new Error(`Servidor do YouTube retornou erro ${xhr.status}. Tente novamente em alguns minutos.`));
            } else {
                let msg = `Upload falhou (HTTP ${xhr.status})`;
                try { msg = JSON.parse(xhr.responseText).error?.message || msg; } catch {}
                reject(new Error(msg));
            }
        };

        xhr.onerror = () => {
            reject(new Error(
                "Erro de rede durante o upload do vídeo. Verifique sua conexão de internet e tente novamente."
            ));
        };
        
        xhr.ontimeout = () => {
            reject(new Error("Upload do vídeo excedeu o tempo limite. Verifique sua conexão e tente com um arquivo menor."));
        };
        
        xhr.onabort = () => {
            reject(new Error("Upload foi cancelado."));
        };

        // No timeout for large uploads
        xhr.timeout = 0;
        xhr.send(file);
    });
}

/**
 * Upload thumbnail — best effort, never blocks the pipeline.
 * Supports both data URLs and blob URLs.
 */
async function uploadThumbnail(token: string, videoId: string, thumbnailSource: string) {
    console.log("[YouTube] Enviando thumbnail…");
    try {
        let blob: Blob;
        
        if (thumbnailSource.startsWith("data:")) {
            blob = await (await fetch(thumbnailSource)).blob();
        } else if (thumbnailSource.startsWith("blob:")) {
            blob = await (await fetch(thumbnailSource)).blob();
        } else {
            // Regular URL — try to fetch
            const res = await fetch(thumbnailSource);
            blob = await res.blob();
        }

        if (blob.size === 0) {
            console.warn("[YouTube] ⚠️ Thumbnail vazia, pulando upload.");
            return;
        }

        const res = await fetch(
            `https://www.googleapis.com/upload/youtube/v3/thumbnails/set?videoId=${videoId}`,
            {
                method: "POST",
                headers: {
                    Authorization: `Bearer ${token}`,
                    "Content-Type": blob.type || "image/jpeg",
                },
                body: blob,
            }
        );
        
        if (res.ok) {
            console.log("[YouTube] ✅ Thumbnail enviada com sucesso.");
        } else {
            const err = await res.json().catch(() => ({}));
            console.warn("[YouTube] ⚠️ Falha na thumbnail (não crítico):", err.error?.message || `HTTP ${res.status}`);
        }
    } catch (e: any) {
        console.warn("[YouTube] ⚠️ Erro ao enviar thumbnail (não crítico):", e.message);
    }
}
